### PR TITLE
Celestial Intersection time update

### PR DESCRIPTION
**Pull request by Arokha**
5.1 changed it from 60s to 30s

### CODE REVIEW

**Comment by Arokha** [comment]
I think your CI is broken. Or `master` doesn't build.

**Comment by Aho-Senpai** [comment]
Will check tomorrow

**Comment by paissaheavyindustries** [comment]
Yeah the CI is broken atm, master builds but since the project files had some changes the CI script doesn't find everything it needs. I'll look into it when I have time

**Comment by Aho-Senpai** [comment]
CI recast got fixed, will let @paissaheavyindustries close the pull request if needed

**Pull request closed without merging**
